apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-1
  name: auth-1
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: auth-1
    spec:
      containers:
      - env:
          - name: DJANGO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: DJANGO_SECRET_KEY
                name: auth-dj-secret-key
        name: auth-sha256-01
        image: gcr.io/PROJECT_ID/IMAGE:TAG
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: auth-1
  name: auth-1-hpa
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-1

