version: "3.9"

services:

  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    links:
      - memchached
      - postgres

  memchached:
    image: library/memcached:alpine
    ports:
      - "11211:11211"

  postgres:
    image: library/postgres:13.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}