from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView
from rest_framework_simplejwt.views import TokenRefreshView

from .viewsets import UserView, RegisterView, ScopeTokenObtainPairView

urlpatterns = [
    path("auth/api/", include("rest_framework.urls"), name="auth_login"),
    path("auth/user/", UserView.as_view(), name="user_detail"),
    path("auth/admin/", admin.site.urls, name="admin"),
    path("auth/token/", ScopeTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/register/", RegisterView.as_view(), name="register"),
    # swagger and redoc autogenerated api schema
    path("api/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
    path("api/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
]
